# Generated by Django 5.0.2 on 2024-02-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=100)),
                ('lesson_description', models.TextField()),
                ('content', models.JSONField()),
            ],
        ),
    ]
